server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/project?useSSL=false&useUnicode=true&charcterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 190591071

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: edu.wbu.pojo
